controller_list:
  - name: whole_body_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_roll
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_roll
      - r_footjoint_roll
      - r_footjoint_pitch
      - r_ankle_pitch
      - r_ankle_roll
      - l_footjoint_roll
      - l_footjoint_pitch
      - l_ankle_pitch
      - l_ankle_roll