controller_list:
  - name: fake_r_arm_controller
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_roll
  - name: fake_l_arm_controller
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_roll
  - name: fake_l_leg_controller
    joints:
      - l_footjoint_roll
      - l_footjoint_pitch
      - l_ankle_pitch
      - l_ankle_roll
  - name: fake_r_leg_controller
    joints:
      - r_footjoint_roll
      - r_footjoint_pitch
      - r_ankle_pitch
      - r_ankle_roll
  - name: fake_whole_body_controller
    joints:
      - l_footjoint_roll
      - l_footjoint_pitch
      - l_ankle_pitch
      - l_ankle_roll
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_roll
      - r_footjoint_roll
      - r_footjoint_pitch
      - r_ankle_pitch
      - r_ankle_roll
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_roll
  - name: fake_whole_body_tips_controller
    joints:
      - l_footjoint_roll
      - l_footjoint_pitch
      - l_ankle_pitch
      - l_ankle_roll
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_elbow_roll
      - r_footjoint_roll
      - r_footjoint_pitch
      - r_ankle_pitch
      - r_ankle_roll
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_elbow_roll