whole_body_fixed:
  kinematics_solver: whole_body_kinematics_plugin/WholeBodyKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver_search_resolution: 0.005
  #kinematics_solver_timeout: 0.005
  #kinematics_solver_attempts: 3
  kinematics_solver_ik_links:
    - l_arm_endcoords
    - r_arm_endcoords
    - l_foot_endcoords
    - r_foot_endcoords
  kinematics_solver_max_solver_iterations: 500 # how many times to perform newton raphson iterations before trying a different seed state 500
  #kinematics_solver_timeout: 0.005 # amount of time allowed before giving up
  kinematics_solver_verbose: false #false
  kinematics_solver_debug_mode: false #false
  kinematics_solver_visualize_search: false #false
  kinematics_solver_epsilon: 0.0001 #1e-5   # how close the end effector position has to be before it is considered solved 1e-5
  kinematics_solver_null_space_epsilon: 0.001 #1e-3
  kinematics_solver_null_space_vel_gain: 0.001 #1e-3
  kinematics_solver_ee_pos_vel_limit: 0.1 #0.1
  kinematics_solver_ee_rot_vel_limit: 1 # essentially turned off 1.5
  kinematics_solver_joint_velocity_max_ratio: 0.1 #0.1
l_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
r_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
l_leg:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
r_leg:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

r_leg_test:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPluginnn
  #kinematics_solver: b3w_whole_body_ik_plugin/B3wWholeBodyIkPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3