b3w_walker:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50   
  
  r_shoulder_pitch_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_pitch
  r_shoulder_roll_controller:
    type: position_controllers/JointPositionController
    joint: r_shoulder_roll
  r_elbow_roll_controller:
    type: position_controllers/JointPositionController
    joint: r_elbow_roll 
  l_shoulder_pitch_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_pitch
  l_shoulder_roll_controller:
    type: position_controllers/JointPositionController
    joint: l_shoulder_roll
  l_elbow_roll_controller:
    type: position_controllers/JointPositionController
    joint: l_elbow_roll
  r_footjoint_roll_controller:
    type: position_controllers/JointPositionController
    joint: r_footjoint_roll
  r_footjoint_pitch_controller:
    type: position_controllers/JointPositionController
    joint: r_footjoint_pitch
  r_b_footjoint_pitch_controller:
    type: position_controllers/JointPositionController
    joint: r_b_footjoint_pitch
  r_uf_knee_controller:
    type: position_controllers/JointPositionController
    joint: r_uf_knee
  r_db_knee_controller:
    type: position_controllers/JointPositionController
    joint: r_db_knee
  r_df_knee_controller:
    type: position_controllers/JointPositionController
    joint: r_df_knee
  r_ankle_pitch_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_pitch
  r_ankle_roll_controller:
    type: position_controllers/JointPositionController
    joint: r_ankle_roll
  l_footjoint_roll_controller:
    type: position_controllers/JointPositionController
    joint: l_footjoint_roll
  l_footjoint_pitch_controller:
    type: position_controllers/JointPositionController
    joint: l_footjoint_pitch
  l_b_footjoint_pitch_controller:
    type: position_controllers/JointPositionController
    joint: l_b_footjoint_pitch
  l_uf_knee_controller:
    type: position_controllers/JointPositionController
    joint: l_uf_knee
  l_db_knee_controller:
    type: position_controllers/JointPositionController
    joint: l_db_knee
  l_df_knee_controller:
    type: position_controllers/JointPositionController
    joint: l_df_knee
  l_ankle_pitch_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_pitch
  l_ankle_roll_controller:
    type: position_controllers/JointPositionController
    joint: l_ankle_roll
